name: Deploy greetings app
description: Stop old app and start python-greetings with pm2

inputs:
  working-directory:
    required: true
    description: Directory where python-greetings repo is checked out
  env-name:
    required: true
    description: Environment name
  port:
    required: true
    description: App port

runs:
  using: composite
  steps:
    - name: Print deploy stage
      shell: bash
      run: echo "Deploying application to ${{ inputs.env-name }} environment..."

    - name: Stop old service
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pm2 delete greetings-app-${{ inputs.env-name }} || true

    - name: Start app
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pm2 start app.py --name greetings-app-${{ inputs.env-name }} --interpreter ./venv/bin/python -- --port ${{ inputs.port }}
