name: Test greetings app
description: Install test deps and run greetings tests

inputs:
  working-directory:
    required: true
    description: Directory where test repo is checked out
  env-name:
    required: true
    description: Environment name
  base-url:
    required: true
    description: Base URL for tested environment

runs:
  using: composite
  steps:
    - name: Print test stage
      shell: bash
      run: echo "Running tests on ${{ inputs.env-name }} environment..."

    - name: Prepare local npm cache
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p .npm-cache

    - name: Install npm deps
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        npm_config_cache: ${{ github.workspace }}/${{ inputs.working-directory }}/.npm-cache
      run: |
        npm install

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        BASE_URL: ${{ inputs.base-url }}
        npm_config_cache: ${{ github.workspace }}/${{ inputs.working-directory }}/.npm-cache
      run: |
        npm run greetings greetings_${{ inputs.env-name }}
