name: Python Greetings Pipeline

on:
  push:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Install pip dependencies
        uses: ./.github/actions/setup-python-env
        with:
          repo-path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Deploy to dev
        uses: ./.github/actions/deploy-greetings
        with:
          env-name: dev
          port: 7001
          repo-path: python-greetings

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Tests on dev
        uses: ./.github/actions/test-greetings
        with:
          env-name: dev
          base-url: http://localhost:7001
          repo-path: tests

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Deploy to stg
        uses: ./.github/actions/deploy-greetings
        with:
          env-name: stg
          port: 7002
          repo-path: python-greetings

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - name: Tests on stg
        uses: ./.github/actions/test-greetings
        with:
          env-name: stg
          base-url: http://localhost:7002
          repo-path: tests

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - name: Deploy to preprod
        uses: ./.github/actions/deploy-greetings
        with:
          env-name: preprod
          port: 7003
          repo-path: python-greetings

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Tests on preprod
        uses: ./.github/actions/test-greetings
        with:
          env-name: preprod
          base-url: http://localhost:7003
          repo-path: tests

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Deploy to prod
        uses: ./.github/actions/deploy-greetings
        with:
          env-name: prod
          port: 7004
          repo-path: python-greetings

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Tests on prod
        uses: ./.github/actions/test-greetings
        with:
          env-name: prod
          base-url: http://localhost:7004
          repo-path: tests
